sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t ethereum/casper:test .

script:
  - docker run -it --rm ethereum/casper:test pytest pyethereum/ethereum/tests/hybrid_casper/test_chain.py